name: admin_board
description: A cross-platform admin board with CRUD functionality

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  fl_chart: ^0.70.2
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^4.0.4
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  permission_handler: ^10.2.0
  universal_html: ^2.2.4
  open_file: ^3.5.10
  
flutter:
  uses-material-design: true