name: admin_board
description: A cross-platform admin board with CRUD functionality

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5

flutter:
  uses-material-design: true